apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  replicas: 2
  template:
    metadata:
      name: nginx-pod
      labels: 
        app: nginx1
    spec:
      containers:
        - name: nginx-container
          image: acrparalaboratoriodevops.azurecr.io/devopslab:latest
          ports: 
           - containerPort: 80
  selector:
    matchLabels:
      app: nginx1


---
apiVersion: v1
kind: Service
metadata:
  name: nginx-deploy-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: nginx-deploy
  ports:
    - port: 80
      targetPort: 80


